# Alternative deployment method using peaceiris/actions-gh-pages
# Use this if the main deploy.yml doesn't work for you
# To use this, rename this file to deploy.yml and delete the other one

name: Deploy to GitHub Pages (Alternative)

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: false
          enable_jekyll: false





